spring:
  application:
    name: ms-hystrix-tubine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8031
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka      # 将自己注册到peer2这个Eureka上面去
